### ISSUE TITLE
Getting error zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by mnh48** [pepijndevos/citiesheightmap#1]
Here's the command used and the output I got
```console
test@TEST:/test$ python3 heightmap.py test 3.148628 101.694204
Namespace(blur=2, height_scale=64, lat=3.148628, lon=101.694204, name='test', seabed=-10, sealevel=40, span=18, water=True)
BBox(top=3.2319613333333335, bottom=3.0652946666666665, left=101.6107446775582, right=101.7776633224418)
Downloading https://s3.amazonaws.com/elevation-tiles-prod/skadi/N03/N03E101.hgt.gz
Downloading https://dds.cr.usgs.gov/srtm/version2_1/SWBD/SWBDeast/e101n03e.zip
Traceback (most recent call last):
  File "heightmap.py", line 196, in <module>
    a = get_bounds(bbox, args.water)
  File "heightmap.py", line 136, in get_bounds
    download_zip(paths.water_url)
  File "heightmap.py", line 55, in download_zip
    z = zipfile.ZipFile(io.BytesIO(r.content))
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

I tried to download manually in case the problem is actually broken download
and it seemed like the second link that the script was trying to download
( https://dds.cr.usgs.gov/srtm/version2_1/SWBD/SWBDeast/e101n03e.zip )
doesn't give zip file, it just gave this page instead
![image](https://user-images.githubusercontent.com/12217018/111884634-dfd5e400-89fd-11eb-8a43-e5773793302a.png)

**Comment by pepijndevos** [comment]
Annoying. Well, you'll have to find another source of the srtm data then.
https://wiki.openstreetmap.org/wiki/SRTM
